# Generated by Django 3.2.7 on 2021-09-17 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('actualizacion', models.DateField(auto_now_add=True)),
                ('autorizante', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.administrador')),
                ('estudiantepulicador', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.estudiante')),
            ],
        ),
    ]
