# Generated by Django 3.2.7 on 2021-09-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_articulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('actualizacion', models.DateField(auto_now_add=True)),
                ('articulo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.articulos')),
                ('estudiante', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.estudiante')),
            ],
        ),
    ]
