# Generated by Django 3.2.7 on 2021-09-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_administrador_fotoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='publicacion',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
